- name: install nginx
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: install nginx redhat
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "Redhat"
    
    - name: install nginx debian
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"