- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: install mentioned packages
      ansible.builtin.debug:
        name: "{{ item }}"
        state: present
      loop:
        - gcc
        - mysql
        - git
        - zip
